plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '4.0.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.neatore.weeklycomma'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

springBoot {
    mainClass = 'org.neatore.weeklycomma.WeeklyComma'
}

repositories {
    mavenCentral()
}

dependencies {
    // starters
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // logging
    implementation 'org.apache.logging.log4j:log4j-core:2.25.4'

    // json
    implementation 'org.json:json:20251224'

    // database
    implementation 'org.xerial:sqlite-jdbc:3.51.2.0'
    implementation 'org.hibernate.orm:hibernate-community-dialects:7.2.6.Final'

    // tools
    implementation 'org.projectlombok:lombok'
    implementation 'com.google.api-client:google-api-client:2.9.0'
    implementation 'commons-codec:commons-codec:1.21.0'
    // - jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-gson:0.13.0'

    annotationProcessor 'org.projectlombok:lombok'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
